OnlineExam/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;

namespace OnlineExam.Models
{
    public class AppUser : IdentityUser
    {
        public string FullName { get; set; }

        public List<ExamResult> ExamResults { get; set; }
    }
}

OnlineExam/Controllers/AppUserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineExam.Models;

namespace OnlineExam.Controllers
{
    public class AppUserController : Controller
    {
        private readonly AppDBContext _context;
        private readonly UserManager<AppUser> _userManager;

        public AppUserController(AppDBContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        public IActionResult Index()
        {
            if (TempData["User"] != null)
            {
                string user = TempData["User"].ToString();
                ViewBag.exams = _context.Exams.ToList();
                List<ExamResult> results = _context.ExamResults.Where(x => x.AppUserID == user).ToList(); ;
                return View(results);
            }

            return View();

            


           
        }

        public IActionResult Sinavlar(string? id,int ExamID)
        {
            TempData["User"] = id;
            TempData["Examid"] = ExamID;
            ViewBag.dersAdi = _context.Exams.FirstOrDefault(x => x.ExamId == ExamID).ExamName;

           List<QuestionAndOptions> model= _context.QuestionsAndOptions.Where(x=>x.ExamId==ExamID).ToList();
            return View(model);
        }

        [HttpPost]
        public IActionResult Sinavlar(List<QuestionAndOptions> questionAndOptions, int ExamID,string? id)
        {
            ExamID = Convert.ToInt32(TempData["Examid"]);
            id = TempData["User"].ToString();
            int result = 0;
            int correctCount = 0;
            int wrongCount = 0;
            foreach (QuestionAndOptions question in questionAndOptions)
            {
                if (_context.QuestionsAndOptions.Any(x=>x.CorrectAnswer==question.SelectedOption))
                {
                    result = result + 20;
                    correctCount++;
                }
                else
                {
                    wrongCount++;
                }
               
            };
            ExamResult examResult = new ExamResult()
            {
                AppUserID = id,
                ExamId= ExamID,
                CorrectCount=correctCount,
                WrongCount=wrongCount,
                Result=result,

            };
            _context.ExamResults.Add(examResult);
            _context.SaveChanges();
            
            return RedirectToAction("Index");
        }

    }
}

OnlineExam/Views/AppUser/Index.cshtml
@*

    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = "_EmptyLayout";
    List<Exam> exams = ViewBag.exams;
}
@model List<ExamResult>
@Html.ActionLink("Matematik vize Sınavına Git","Sinavlar",new{ExamID=1,id=TempData["User"].ToString()})
<br />
@Html.ActionLink("Kimya vize sınavına git Git","Sinavlar",new{ExamID=4,id=TempData["User"].ToString()})
<br />
@Html.ActionLink("Matematik final sınavına git Git","Sinavlar",new{ExamID=5,id=TempData["User"].ToString()})

<div class="panel-body">
    <div class="adv-table">
        <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
            <thead>
                <tr>
                    <th>Doğru Sayısı</th>
                    <th>Yanlış Sayısı</th>
                    <th>Puan</th>
                    <th class="hidden-phone">Sınav/Ders Adı</th>
                    
                </tr>
            </thead>
            <tbody>
                @if (Model!=null)
                {
                    @foreach (var item in Model)
                    {
                        <tr class="gradeX">

                            <td>@item.CorrectCount</td>
                            <td class="center hidden-phone">@item.WrongCount</td>
                            <td class="center hidden-phone">@item.Result</td>
                            @{
                                string deger = exams.FirstOrDefault(x => x.ExamId == item.ExamId).ExamName;
                            }

                            <td class="center hidden-phone">@deger</td>



                        </tr>
                    }
                }
               
            </tbody>
        </table>

    </div>
</div>

OnlineExam/Views/AppUser/Sinavlar.cshtml
@model List<QuestionAndOptions>
@{
    ViewData["Title"] = "Sinavlar";
    Layout = "_EmptyLayout";
    int sayi = 1;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Timer</title>
</head>
<body>

    <h1 id="timer">0:00</h1>

    <script >
        let seconds = 0;
        let minutes = 10; // 10 dakika
        let display = document.getElementById('timer');

        function startTimer() {
            displayTimer();
            setInterval(updateTimer, 1000);
        }

        function updateTimer() {
            if (seconds > 0) {
                seconds--;
            } else {
                if (minutes === 0) {
                    clearInterval(); // Zaman bittiğinde interval'ı durdur
                    alert("Zaman doldu!");
                    return;
                }
                seconds = 59;
                minutes--;
            }
            displayTimer();
        }

        function displayTimer() {
            display.textContent = (minutes < 10 ? '0' + minutes : minutes) + ':' + (seconds < 10 ? '0' + seconds : seconds);
        }

        window.onload = startTimer;

        

    </script>



<form asp-controller="AppUser" asp-action="Sinavlar" method="post">

        <h1>@ViewBag.dersAdi Soruları</h1>
        <br />

    @for (var i = 0; i < Model.Count; i++)
    {
        var item = Model[i];
        <h3>@sayi-) @item.QuestionText</h3>

        <label>
            <input name="questionAndOptions[@i].SelectedOption" type="radio" value="@item.A" />
            @item.A
        </label>
        <br />
        <label>
            <input name="questionAndOptions[@i].SelectedOption" type="radio" value="@item.B" />
            @item.B
        </label>
        <br />
        <label>
            <input name="questionAndOptions[@i].SelectedOption" type="radio" value="@item.C" />
            @item.C
        </label>
        <br />
        <label>
            <input name="questionAndOptions[@i].SelectedOption" type="radio" value="@item.D" />
            @item.D
        </label>

        sayi++;
    }
    <br />
    <button type="submit">Cevapları Onayla!</button>
</form>

</body>
</html>